blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/twangodev/uw-coursemap/discussions/new?category=ideas
    about: Have an idea for a new feature? Share it here!
  - name: Discussions
    url: https://github.com/twangodev/uw-coursemap/discussions
    about: Any questions about how to use the project? Ask here!
